### ISSUE TITLE
Change permissions for generated reports folder; remove public/reports

### ISSUE THREAD

**Issue by jwbowles** [ucfopen/UDOIT#123]
In process.php the $report_directory variable is pointing to the directory above where the reports directory actually exists and causes the report to not be generated. On a side note is there a reason for the chmod 777? I believe 755 should work just fine.

**Comment by bagofarms** [comment]
@jwbowles We'll go in and move the reports directory where the process.php file is looking for it.  Heroku compatibility has had some ripple effects, and we're still finding some of them.  I think the 777 permissions were just left over.  We'll change that to 755 or 775.

**Comment by bagofarms** [comment]
I just did a fresh install of UDOIT on our production server (starting from an empty directory), and had no issues with reports saving.  If the reports folder does not exist, UDOIT will create the folder.  If it doesn't have permission to create the folder, that's when you'll run into issues.  I'm leaving this open, though, because we still need to change the permissions to 775 and remove the old reports folder that still lives in Public.

**Comment by aunglinn** [comment]
```..\udoit\public\process.php 
00066: $report_directory = '../reports/'.$user_id.'/'.$to_encode['course'];
00070: chmod('../reports/'.$user_id, 0777);```
The directory pointing has two "." to point outside the udoit public folder. I think if we change to "./reports/'.$user_id.'/'.$to_encode['course']; should works. Will there be bug fixes for this in later version? Thanks.

**Comment by bagofarms** [comment]
The two "." is intended.  We moved the reports folder to be outside of the public folder so that the reports would not be publicly accessible on Heroku (or any other system that is set up in a similar way).  Unfortunately, we forgot to remove the old reports folder from public.  Please keep that line of code the way it was if you can.  If it is not creating the new reports folder in the root directory, let me know, and we can look into it.

**Comment by aunglinn** [comment]
@bagofarms Thank you. I was confused with the reports folder in the Public folder trying to give permission on it. Later I found out that the script was trying to create reports on different folder. Maybe it could help if there was error showing if the report directory or json file couldn't write on the server. Anyway, UDOIT is a great system.

**Comment by emilysachs** [comment]
No longer relevant with changes in https://github.com/ucfopen/UDOIT/issues/242
