### ISSUE TITLE
Table heading conversion did not happen on Syllabus page

### ISSUE THREAD

**Issue by adrian-goetz** [ucfopen/UDOIT#131]
https://webcourses.ucf.edu/courses/1158846/assignments/syllabus

I selected the "First Column" option in adding table headers.

This is a Course Syllabus, so that may have something to do with it.

**Comment by cooperfellows** [comment]
This is no longer an issue, suggest we close this out.

**Comment by emilysachs** [comment]
Tested this one and found that sometimes the conversion wouldn't work the first time, but would always work when UDOIT and this UFIXIT were run a second time. I believe this issue is related to the conversion of html entities, specifically "&nbsp;" for this one. I haven't been able to trigger the problem consistently enough to solve it yet, though.

**Comment by seanlh** [comment]
Can't access course page, replicated issue by adding &nbsp; to table entries and confirmed that UFIXIT would not set columns or both on first use. Further inspection shows issue #136 is related and fixed in merge request #146.
