### ISSUE TITLE
UDOIT runs continuously on this course:  https://webcourses.ucf.edu/courses/1137338

### ISSUE THREAD

**Issue by bagofarms** [ucfopen/UDOIT#18]
The course doesn't look like it has a ton of files, but maybe one of the files is causing an issue.

**Comment by emilysachs** [comment]
Note: the root of the issue is a GET request that never completes on the improperly formed img src "4637/PHN%20module1_files/rpskhead_nur4832_000076.jpg" found in this file: https://webcourses.ucf.edu/courses/1137338/files/search?preview=46873402&search_term=module
Looking into a way to handle a case like this.

**Comment by bagofarms** [comment]
It looks like JavaScript execution was stopping because a Qualtrics form is embedded in one of the HTML files, which included a script tag that was executing when UDOIT tried to load it into a "View the source of this issue".  Deleting the file that had the qualtrics form allowed UDOIT to display the results.  Stripping out all script tags should solve this issue for good.
