### ISSUE TITLE
Captioning messages different for YouTube and Vimeo?

### ISSUE THREAD

**Issue by inspector508** [ucfopen/UDOIT#315]
I apologize if this has been addressed, but I'm running UDOIT scans for our institution and experiencing some uncertainty about the reporting for YouTube and Vimeo errors. Each service appears once in a scan,  but in one case an error is reported, and in the other, a suggestion appears. Is this a known issue? Does it matter?

![youtube-vimeo-udoit](https://user-images.githubusercontent.com/1102998/33516757-ac576b92-d73d-11e7-95bf-df049d9862e8.jpg)

**Comment by bagofarms** [comment]
Thanks for pointing this out!  This is a known issue, and is due to the fact that we haven't integrated the Vimeo API into UDOIT yet.  With YouTube, we can use the API to determine the presence of human-created captions with certainty.  With Vimeo, we aren't using the API yet, so we can only speculate as to the presence of human-generated captions, hence the "suggestion" instead of an "error".  We have issue #148 open for adding that functionality.
