### ISSUE TITLE
UDOIT video captioning errors with TED and youtube

### ISSUE THREAD

**Issue by Susan-Collins** [ucfopen/UDOIT#367]
UDOIT is showing an error message for every video from youtube and TED, even when they are correctly captioned and followed by a transcript link.  What am I doing wrong?  Is there a fix for this?  I am working in CANVAS.

**Comment by bagofarms** [comment]
Have you added a YouTube API key to your localConfig.php file (or to the Config Vars in Heroku)?  If you do not have an API key, UDOIT will default to warning you about every video.  As for the TED videos, can you give me an example?  Most likely, it's just warning you that you need to check the videos manually since we don't have an integration with TED right now.
