### ISSUE TITLE
Question - Scoped keys variable use

### ISSUE THREAD

**Issue by elearningdave** [ucfopen/UDOIT#496]
More a question this one as I don't know how to do direct messages in github...
Why do you have to tell udoit in the config, that you have enabled the Scoping feature on the API key?

**Comment by bagofarms** [comment]
An excellent question!  It seems I forgot to include that in our README.  If you are using the scoping feature, you'll need to set `$oauth2_enforce_scopes` to `true`

Here is where that value is located in the localConfig template file:
https://github.com/ucfopen/UDOIT/blob/master/config/localConfig.template.php#L11

**Comment by elearningdave** [comment]
It was more from the PHP point of view. Does that effect the programming required to use the API key, or to trigger errors if things fail, or something like that?

**Comment by bagofarms** [comment]
Oh, I'm sorry, I didn't see that you said **why** instead of **where**.

When using scoped developer keys, you have to send different data to Canvas as part of the Oauth2 process.  Specifically, you have to add a `&scope=` parameter to the `redirect_uri` when initiating the Oauth2 process.  Check out the code here:  https://github.com/ucfopen/UDOIT/blob/214bc8c7ef688f6dc2187d5ba7631385a940b5d2/public/index.php#L107
