### ISSUE TITLE
Receive Following Error: Missing Session information

### ISSUE THREAD

**Issue by wliebermanHCC** [ucfopen/UDOIT#543]
When running UDOIT from Canvas, if I run UDOIT from the Navigation menu, I get this error:

Missing Session information. Please refresh the page. Missing: base_url

When I create a Canvas module and add UDOIT as an external tool and run it, I get the exact same error.

But, if I create a Canvas module, add UDOIT as an external tool AND open the tool in a separate window, it works just fine. 

Using Chrome on a Windows 10 laptop.  Any ideas???

**Comment by bagofarms** [comment]
I believe this is due to some recent changes to how Chrome handles cookies.  This was fixed in version [2.6.0](https://community.canvaslms.com/t5/Accessibility/UDOIT-2-6-0-quot-Eatonville-quot/ba-p/270774).  There are two options for fixing this issue in your installation of UDOIT:

1. The best option is to update UDOIT to the latest version, [2.6.4](https://community.canvaslms.com/t5/Accessibility/UDOIT-2-6-4/ba-p/273520)
2. If you can't upgrade right now, you can patch your installation by placing this code right below `define('UDOIT_VERSION'...` in your `config/settings.php` file

**Comment by wliebermanHCC** [comment]
Thank you for the help here.  I really appreciate you getting back to me on this so quickly.  We are going to try the upgrade and see if that fixes the issue.

**Comment by wliebermanHCC** [comment]
This solution WORKED!!!  All is good now.  Thank you!!
