### ISSUE TITLE
Add a detection feature for missing canvas api key.

### ISSUE THREAD

**Issue by phillyc** [ucfopen/UDOIT#66]
@iturgeon and I discussed the utility of detecting if a master api key is present when running the app.

If now, we want to present the user with the ability to paste in their personal developer key.

This would allow them to quickly test UDOIT's capabilities without the need for a master key.

**Comment by bagofarms** [comment]
We talked it over, as well.  I think it's a good idea.  He also mentioned a flag in the localConfig that would allow you to disable the detection feature altogether for a production environment.  That would prevent a real user from being presented with the "insert your own API key" screen.

**Comment by iturgeon** [comment]
Proposed:

* [ ] New template with instructions and input box for user api key
* [ ] New script to process input box data from new template (save these to users table?)
* [ ] New config option $allow_manual_auth_keys default to true(?)
* [ ] detect when $oauth2_key is empty and display new template instead of oauth2 loop

**Comment by bagofarms** [comment]
We haven't implemented this in over 4 years, so I don't think we're going to implement it.
